name: IE7374
channels:
  - conda-forge
  - defaults
  - mro
dependencies:
    - python=3.7
    - pip
    - numpy
    - matplotlib
    - scipy
    - pandas
    - scikit-learn
    - jupyterlab
    - pip:
        - gym
        - tabulate
