name: IE7374
channels:
  - defaults
dependencies:
    - python=3.7.6
    - pip
    - numpy
    - matplotlib
    - scipy
    - pandas
    - scikit-learn
    - notebook
    - pip:
        - gym
        - tabulate
